ServerEvents.recipes(event => {
    event.remove({id: 'mekanism:processing/coal/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/coal/to_ore'})
    event.remove({id: 'mekanism:processing/copper/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/copper/ore/from_raw'})
    event.remove({id: 'mekanism:processing/diamond/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/diamond/to_ore'})
    event.remove({id: 'mekanism:processing/emerald/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/emerald/to_ore'})
    event.remove({id: 'mekanism:processing/fluorite/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/fluorite/to_ore'})
    event.remove({id: 'mekanism:processing/gold/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/gold/ore/from_raw'})
    event.remove({id: 'mekanism:processing/gold/ore/nether_from_raw'})
    event.remove({id: 'mekanism:processing/iron/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/iron/ore/from_raw'})
    event.remove({id: 'mekanism:processing/lapis_lazuli/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/lapis_lazuli/to_ore'})
    event.remove({id: 'mekanism:processing/lead/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/lead/ore/from_raw'})
    event.remove({id: 'mekanism:processing/netherite/dust_to_ancient_debris'})
    event.remove({id: 'mekanism:processing/osmium/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/osmium/ore/from_raw'})
    event.remove({id: 'mekanism:processing/quartz/to_ore'})
    event.remove({id: 'mekanism:processing/redstone/to_deepslate_ore'})
    event.remove({id: 'mekanism:processing/redstone/to_ore'})
    event.remove({id: 'mekanism:processing/tin/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/tin/ore/from_raw'})
    event.remove({id: 'mekanism:processing/uranium/ore/deepslate_from_raw'})
    event.remove({id: 'mekanism:processing/uranium/ore/from_raw'})

})